name: (your name)
recipe: (wordpress) //your recipi (delete comment)
config:
  php: '7.4' //your php (delete comment)
  xdebug: true
  conf:
    php: .vscode/php.ini
tooling:
  'db-import <file>':
    service: :host
    description: Imports a dump file into a database service
    cmd: /helpers/sql-import.sh
    user: root
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      no-wipe:
        description: Do not destroy the existing database before an import
        boolean: false
  