#!/bin/sh

searchr=$(
	zoxide query -l | \
		fzf-tmux -p 60%,50% -i --bind=tab:down --bind=btab:up \
			--bind=ctrl-g:first 
)

if [ -n "$searchr" ]; then
	echo "cd $searchr"
	cd "$searchr" || exit 1
fi
