#!/bin/sh

searchr=$(
	fd --type d --hidden --exclude .git . "$HOME/" | 
		fzf-tmux -p 60%,50% -i --bind=tab:down --bind=btab:up \
			--bind=ctrl-g:first --border=none
)

if [ -n "$searchr" ]; then
	echo "cd $searchr"
	cd "$searchr" || exit 1
fi
