#!/bin/sh

result1=$(
	fd --type f --hidden --exclude .git . "$HOME/" |
		fzf-tmux -p 80%,60% -i --bind=tab:down --bind=btab:up \
			--bind=ctrl-g:first --border=none \
			--preview "bat --color=always --style=numbers --line-range=:500 {}"
)
result2=$(
	fd --type f --hidden --exclude .git . "$HOME/" |
		fzf-tmux -p 80%,60% -i --bind=tab:down --bind=btab:up \
			--bind=ctrl-g:first --border=none \
			--preview "bat --color=always --style=numbers --line-range=:500 {}"
)

if [ -n "$result1" ] && [ -n "$result2" ]; then
	echo "delta $result1  $result2"
	delta "$result1" "$result2" || exit 1
fi
