#!/bin/sh

result1=$(fd --type f --hidden --exclude .git . "$HOME/" | fzf --preview "bat --color=always --style=numbers --line-range=:500 {}")
result2=$(fd --type f --hidden --exclude .git . "$HOME/" | fzf --preview "bat --color=always --style=numbers --line-range=:500 {}")

if [ -n "$result1" ] && [ -n "$result2" ]; then
	echo "delta $result1  $result2"
	delta "$result1" "$result2"
fi
