#!/bin/sh

searchr=$(
	fd --type f --hidden --exclude .git . "$HOME/" |
		fzf-tmux -p 80%,60% -i --bind=tab:down --bind=btab:up \
			-i --bind=tab:down --bind=btab:up \
			--bind=ctrl-g:first \
			--preview "bat --color=always --style=numbers --line-range=:500 {}"
)

if [ -n "$searchr" ]; then
	echo "vim $searchr"
	vim "$searchr" || exit 1
fi
