#!/bin/sh

searchr=$(
  fd --type f --hidden --exclude .git . "$HOME/" |
    fzf-tmux -p 80%,60% -i --bind=tab:down --bind=btab:up \
      -i --bind=tab:down --bind=btab:up \
      --bind=ctrl-g:first \
      --preview "bat --color=always --style=numbers --line-range=:500 {}"
)

[ -n "$searchr" ] && echo "nvim $searchr" && nvim "$searchr" || exit 1
