#!/bin/sh

searchr=$(
	find "$HOME/sites" -maxdepth 1 -type d \( ! -name sites \) -print0 |
		xargs --null -I % basename % |
		fzf-tmux -p 20%,50% -i --bind=tab:down --bind=btab:up \
			--bind=ctrl-g:first --border=none
)

if [ -n "$searchr" ]; then
	cd "$HOME/sites/$searchr" || exit 1
	vim . || exit 1
fi
